dist: trusty
language: python
python:
- '2.7'

virtualenv:
  system_site_packages: true
  
before_install:
- sudo apt-get -u dist-upgrade
- sudo apt-get update
- sudo apt-get install python-numpy python-scipy python-sphinx python-setuptools parallel python-pip python-xlwt python-xlrd imagemagick parallel git-core


install: pip install -r requirements.txt

script:
  - python setup.py test
  - make coverage-gather

after_success:
  coveralls

branches:
  only:
    - master
    - develop
    - release
